Repository jenkinsci/kubernetes-plugin, pull requests merged in 2019-07, with the labels that each got.

#532 Release drafter
  .github/release-drafter.yml
  CHANGELOG.md
Labels: chore

#522 [JENKINS-58290] Verifying ContainerExecDecorator scalability
  pom.xml
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/websocket.groovy
Labels: test

#537 [JENKINS-58374] Properly merge environment variable lists to avoid duplicates
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Labels: bug

#461 [JENKINS-49707] If a KubernetesComputer disconnects, remove the KubernetesSlave
  Jenkinsfile
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/terminatedPod.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/terminatedPodAfterRestart.groovy
Labels: enhancement

#539 [JENKINS-57830] Convenient default for PodTemplateStep.name/label and KubernetesDeclarativeAgent.label
  Jenkinsfile-kubernetes
  Jenkinsfile-release
  README.md
  examples/containerLog.groovy
  examples/declarative-multiple-containers.groovy
  examples/declarative.groovy
  examples/declarative_from_yaml_file/Jenkinsfile
  examples/docker.groovy
  examples/kaniko-declarative.groovy
  examples/kaniko-gcr.groovy
  examples/kaniko.groovy
  examples/maven-with-cache.groovy
  examples/maven-yaml.groovy
  examples/maven.groovy
  examples/multi-container.groovy
  examples/selenium.groovy
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/help-label.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/help-name.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlaveTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecutionUnitTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/badcontainername.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/badcontainernameyaml.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/badlabel.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/bourneShellElsewhereInPath.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/computerCantBeConfigured.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarative.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeCustomWorkspace.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeFromYaml.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeFromYamlFile.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeWithNamespaceFromYaml.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/docker.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/getContainerLog.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/getContainerLogWithRestart.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runDirContext.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodFromYaml.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodNested.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodNestedExplicitInherit.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithDifferentShell.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithLivenessProbe.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithMultipleContainers.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithRestart.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithRestartWithLongSleep.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithRestartWithMultipleContainerCalls.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithRetention.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithShowRawYamlFalse.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithCloudOverriddenNamespace.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithEnvVariables.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithEnvVariablesInContext.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithOverriddenEnvVariables.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithStepOverriddenNamespace.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/sshagent.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/supportComputerEnvVars.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/websocket.groovy
Labels: enhancement

#531 [JENKINS-42763] Only override HOME if OpenShift
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Messages.properties
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Labels: bug

#541 ExtensionList.lookupSingleton
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateMap.java
Labels: chore

#540 Use POD_LABEL for the plugin CI
  Jenkinsfile-kubernetes
Labels: chore

#542 [JENKINS-58405] Backward compatibility for yaml field merge
  README.md
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Merge.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Overrides.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/YamlMergeStrategy.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-yamlMergeStrategy.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Merge/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Overrides/config.jelly
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/mergeYaml.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/overrideYaml.groovy
Labels: bug

#553 Try to address ContainerExecDecoratorTest#testCommandExecution flakiness
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Labels: test

#551 [JENKINS-58670] Pod Labels UI
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodLabel.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-podLabels.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodLabel/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodLabel/config_zh_CN.properties
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodLabel/help-key.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodLabel/help-value.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_17_2/config.xml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_17_2/credentials.xml
Labels: feature

#554 Demonstrating that an upstream fix avoids the need for a workaround
  pom.xml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithCloudOverriddenNamespace.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithStepOverriddenNamespace.groovy
Labels: test

#562 [JENKINS-58724] Update existing logger to display current run
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
Labels: enhancement

#559 [JENKINS-58705] Update default working dir to /home/jenkins/agent
  README.md
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-workingDir.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly
  src/main/webapp/help/workingDir.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/supportComputerEnvVars.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-overrides.yaml
Labels: bug

#561 [JENKINS-58513] Remove this assertion
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Labels: test

#560 Use the BOM for some dependency management
  pom.xml
Labels: dependencies

#558 [JENKINS-58540] Mask secrets only if non-empty
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithExistingTemplate.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithEnvVariables.groovy
Labels: bug

#563 More BOM
  pom.xml
Labels: dependencies
