Repository jenkinsci/kubernetes-plugin, pull requests merged in 2019-12, with the labels that each got.

#654 Setup namespace if needed and possible in declarative test
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineOverridenNamespaceTest.java
Labels: test

#660 Ensure retention timeout is always >= 5
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-retentionTimeout.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest/minRetentionTimeoutReadResolve/config.xml
Labels: bug

#663 Only keep logs from agents
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#609 Update workflow-step-api to 2.21 - No more need for useBeta
  pom.xml
Labels: dependencies

#610 [JENKINS-58975] - Update the working directory to match container working directory
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeCustomWorkingDir.groovy
Labels: enhancement, ready

#640 [JENKINS-60088] set label "jenkins/label=<label>" instead of "jenkins/<label>=true"
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: enhancement, ready
