Repository jenkinsci/kubernetes-plugin, pull requests merged in 2019-10, with the labels that each got.

#608 PodTemplate’s copy constructor was incomplete
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateFilterTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateTest.java
Labels: bug

#611 Tweaking the pvc test to make it work in the test environment
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVC.groovy
Labels: test

#503 [JENKINS-57993] Verify no warnings are printed for a basic build
  pom.xml
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#614 UI for dynamic pvc
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume/help-accessModes.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume/help-requestsSize.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume/help-storageClassName.html
Labels: enhancement

#622 Always define an explicit workspace volume, it defaults to an empty dir
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/EmptyDirWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/HostPathWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/NfsWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/PersistentVolumeClaimWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/WorkspaceVolume.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Labels: bug

#602 Enable direct connections to TCP agent listener
  README.md
  README_zh.md
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-directConnection.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
  src/test/resources/kubenamespace
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVC.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithLivenessProbe.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithMultipleContainers.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithCloudOverriddenNamespace.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithStepOverriddenNamespace.groovy
Labels: enhancement

#621 [JENKINS-47827] Pod and container runAsUser and runAsGroup
  README.md
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-busybox.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-overrides.yaml
Labels: enhancement

#624 Fix a typo in the REAME.md
  README.md
Labels: chore

#628 Fixed "IllegalStateException: Jenkins URL null" in PodTemplateStepExecution
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: bug

#625 Add support for the spec.hostNetwork field
  README.md
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Labels: enhancement

#631 Use explicitly a more recent jnlp-slave to avoid problems with cached…
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Labels: chore

#633 Switch directConnection default to false
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
Labels: bug
