Repository jenkinsci/kubernetes-plugin, pull requests merged in 2019-11, with the labels that each got.

#638 Add support for yamlMergeStrategy in declarative pipelines
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
Labels: enhancement

#639 Fix wording and typos in No delay provisioning section
  README.md
Labels: chore

#642 Fix a few spelling errors in the README
  README.md
Labels: chore

#643 Allow runAsUser and runAsGroup to be set from the PodTemplateStep
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
Labels: enhancement

#645 [JENKINS-60042] Restore delete button to pod template list
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
Labels: bug

#649 avoiding flake: RejectedAccessException: Scripts not permitted to use staticMethod org.jenkinsci.plugins.workflow.cps.Safepoint safepoint
  pom.xml
Labels: chore

#655 Safepoint flakes, redux
  pom.xml
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test
