Repository jenkinsci/kubernetes-plugin, pull requests merged in 2020-03, with the labels that each got.

#724 Do not assert $JNLP_JAVA_HOME
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#728 Set default cpu & memory requests on the jnlp container
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Labels: enhancement

#727 Validation for ContainerTemplate.image
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplateTest.java
Labels: enhancement

#726 Allow setting of workspaceVolume in declarative Jenkins pipeline
  README.md
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
Labels: enhancement

#730 Fix copy constructor of PodTemplate to keep TaskListener
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
Labels: bug

#729 Fix packaging of unwanted dependencies
  pom.xml
Labels: bug

#735 [JENKINS-58732] Update pipeline-model-definition & drop explicit dep on docker-workflow
  pom.xml
Labels: dependencies

#739 Fix typo, add newline to end of file
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-directConnection.html
Labels: documentation

#736 Removing warning about container step
  README.md
Labels: documentation

#703 [JENKINS-57828] Cleaning up the Snippet Generator output for PodTemplateStep
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly
  src/main/webapp/help/inheritFrom.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepTest.java
Labels: enhancement

#740 Agent should be terminated since the queue item asking for it is removed
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Labels: bug

#742 Log events in build log during pod provisioning
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/TaskListenerEventWatcher.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  test-in-k8s.yaml
Labels: enhancement

#744 Change StatefulSet apiVersion
  src/main/kubernetes/jenkins.yml
Labels: documentation

#745 Any Secret File credential can be be used for any kubeconfig, not just AKS
  README.md
Labels: documentation

#746 Fill credentials from current context instead of just Jenkins singleton
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Labels: enhancement

#748 jenkins.version=2.222.1
  pom.xml
Labels: dependencies
