Repository jenkinsci/kubernetes-plugin, pull requests merged in 2020-12, with the labels that each got.

#851 Specify jnlp container limits through system properties
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
Labels: enhancement

#869 [JENKINS-63016] feat: new resource - ephemeral storage
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly
Labels: enhancement

#906 Pod decorator extension point
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/DefaultNodeSelector.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/DefaultRestartPolicy.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/DefaultWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/PodDecorator.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/PodDecoratorTest.java
Labels: enhancement

#913 Get rid of explicit labels in declarative tests
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeCustomWorkingDir.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeCustomWorkspace.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeFromYaml.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeWithNamespaceFromYaml.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeWithNestedExplicitInheritance.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeWithNonexistentDockerImage.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeWithNonexistentDockerImageLongLabel.groovy
Labels: test

#918 Update jackson2-api to 2.12.0
  pom.xml
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/octalPermissions.groovy
Labels: dependencies

#919 Adding zero as "no limit value" for cap
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-instanceCap.html
Labels: bug

#915 [JENKINS-57841] Change defaults for command and args
  examples/kaniko-declarative.groovy
  examples/kaniko-gcr.groovy
  examples/multi-container.groovy
  examples/openshift-home-yaml.groovy
  examples/selenium.groovy
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-args.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-command.html
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarative.groovy
Labels: enhancement
