Repository jenkinsci/kubernetes-plugin, pull requests merged in 2020-02, with the labels that each got.

#706 Remove versions overrides from dependency management
  pom.xml
Labels: dependencies

#709 Randomize ports used by test-in-k8s
  test-in-k8s.sh
  test-in-k8s.yaml
Labels: test

#708 Use Serialization.asYaml when printing API resources to log
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
Labels: enhancement

#710 Reduce log verbosity when running tests
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java
Labels: test

#707 Using GroovySample extension point
  examples/README.md
  examples/declarative-multiple-containers.groovy
  examples/declarative.groovy
  examples/maven-yaml.groovy
  examples/maven.groovy
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesSamples.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/declarative.groovy
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/maven.groovy
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/windows.groovy
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesSamplesTest.java
Labels: feature

#713 [JENKINS-60977] Drop the working dir migration
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java
Labels: bug

#714 Clean up reaper watch during test to avoid spam
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
Labels: test

#712 Remove calls to PodTemplate#getDisplayName and use #getName instead.
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/StandardPlannedNodeBuilder.java
Labels: enhancement

#497 [JENKINS-53790] PodTemplate Container Docker image check
  .gitignore
  README.md
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/InvalidDockerImageException.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeWithNonexistentDockerImage.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeWithNonexistentDockerImageLongLabel.groovy
Labels: enhancement

#695 [JENKINS-60105] More aggressive cleanup to prevent UX issues running against EKS
  README.md
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Labels: enhancement

#715 Make KubernetesSamples extensions optional
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesSamples.java
Labels: bug

#716 Adding generic setup configuration to the README.md
  README.md
  Screen Shot 2020-02-20 at 2.00.28 PM.png
  Screen Shot 2020-02-20 at 2.01.48 PM.png
Labels: chore

#718 Remove warning about high number of expired clients
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
Labels: test

#717 [JENKINS-61178] When defining an extra container in a pod template with a custom working dir, it is wrongly used as the node working dir
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/sidecarWorkingDir.groovy
Labels: bug

#661 [JEP-222] Pass JENKINS_WEB_SOCKET when so configured
  README.md
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-webSocket.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/WebSocketTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/closedWebSocketExit.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/webSocketAgent.groovy
Labels: feature

#721 One more flake
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Labels: test
