Repository jenkinsci/kubernetes-plugin, pull requests merged in 2020-05, with the labels that each got.

#774 Kind 0.8.0
  kind.sh
Labels: chore

#778 Add steps to debug hanged pipeline sh step into README.md
  README.md
Labels: documentation

#776 Fix broken link to windows pipeline example in README.md
  README.md
Labels: documentation

#777 Add support for optional secret environment variables
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/model/SecretEnvVar.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/ConfigMapVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/model/SecretEnvVar/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/model/SecretEnvVar/config_zh_CN.properties
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/model/SecretEnvVar/help-optional.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/ConfigMapVolume/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/ConfigMapVolume/config_zh_CN.properties
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/ConfigMapVolume/help-optional.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume/help-optional.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Labels: enhancement

#779 Do not put agent temporarily offline before deleting it
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Labels: enhancement

#782 Add selector to yaml file of statefullset
  src/main/kubernetes/jenkins.yml
Labels: documentation

#781 Don't use Computer#getLogDir to avoid race condition
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#772 [JENKINS-59340] Terminate agent when a container is terminated
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/InvalidDockerImageException.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/containerTerminated.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/podDeadlineExceeded.groovy
Labels: enhancement

#784 Relax test check
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#783 Re-inject taskListener after Jenkins restart to keep getting logs
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Labels: enhancement

#786 Make containerTerminated more reliable
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/containerTerminated.groovy
Labels: test

#753 Removing docker 'slave' ref.. New image is inbound-agent
  README.md
Labels: documentation
