Repository jenkinsci/kubernetes-plugin, pull requests merged in 2020-09, with the labels that each got.

#830 Update DinD Example
  examples/dind.groovy
Labels: documentation

#834 Fix incorrect permission checks in KubernetesComputer views
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/container.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/events.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/podLog.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/sidepanel2.jelly
Labels: bug

#836 [JENKINS-63584] Add an option to use Jenkins proxy to access Kubernetes
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-useJenkinsProxy.html
Labels: enhancement

#840 Handle compatibility with 2.238 introducing Agent/ExtendedRead
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#841 [JENKINS-63359] Add a unique ID to pod template.
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/taskListenerAfterRestart_multipleLabels.groovy
Labels: bug

#846 Poll for template availability for a few seconds once the pipeline is ready to run
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Labels: test

#844 [JENKINS-63705] [JENKINS-59959] Reverting change to concurrency limits in 1.27.1
  src/main/java/io/jenkins/plugins/kubernetes/NoDelayProvisionerStrategy.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  test-in-k8s.sh
Labels: bug

#847 Ignore `KubernetesPipelineTest#computerCantBeConfigured`
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#849 Remove `workflow-cps` override
  pom.xml
Labels: dependencies
