Repository jenkinsci/kubernetes-plugin, pull requests merged in 2020-11, with the labels that each got.

#859 Don't set nodeSelector when `.spec.runtimeClassName` is set
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Labels: enhancement

#835 Rework concurrency limits using the number provided in Cloud API
  pom.xml
  src/main/java/io/jenkins/plugins/kubernetes/NoDelayProvisionerStrategy.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: enhancement

#882 Test for SECURITY-1646
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/substituteEnv.groovy
Labels: test

#880 Resolve cloud when removing dynamic template
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPod.groovy
Labels: bug

#886 Backport: Fix template removal
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPod.groovy
Labels: bug

#888 Add more logs to tests in order to diagnose flakiness
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#891 fix: getPodRetention throws IllegalArgumentException
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Labels: bug

#894 Update kind to 0.9.0
  kind.sh
Labels: chore

#889 Simplify caching by removing the close logic
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
Labels: bug

#890 [JENKINS-61931] Add ability to set docker registry prefix for default JNLP image
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Labels: enhancement

#892 Add a QueueListener triggering node provisioning
  src/main/java/io/jenkins/plugins/kubernetes/NoDelayProvisionerStrategy.java
Labels: enhancement

#895 Log cloud name to launching logs
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Labels: enhancement

#898 Slow down a bit the provisioning in tests as I've seen some overprovisioning.
  pom.xml
Labels: test

#871 Resurrecting KubernetesPipelineTest.runInPodWithDifferentShell
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithDifferentShell.groovy
Labels: test

#897 Improve tests logging
  pom.xml
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#902 KubernetesCloud.provision optimizations
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateLabelFilter.java
Labels: bug

#901 Assert we have only one kubernetes cloud after casc has run
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/CasCTest.java
Labels: test

#903 Handle migration of `containerCap = 0`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest/readResolveContainerCapZero/config.xml
Labels: bug

#907 If credentialsId is specified, signal an error if no such credentials actually exists
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
Labels: bug

#909 getJenkinsUrlOrNull to ignore KUBERNETES_JENKINS_URL when webSocket && credentialsId
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Labels: enhancement

#908 testConnection should display gitVersion rather than major.minor
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Labels: enhancement

#910 Remove @Restricted for PodTemplate#getYaml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
Labels: chore
