Repository jenkinsci/kubernetes-plugin, pull requests merged in 2020-01, with the labels that each got.

#644 Add supplemental groups support to PodTemplates
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep/config.jelly
  src/main/webapp/help/supplementalGroups.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Labels: enhancement

#671 [JENKINS-60517] Add null check for containerWorkingDirFilePath
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInDynamicallyCreatedContainer.groovy
Labels: bug

#679 Log name of pod template instead of generic value
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Labels: enhancement

#677 [JENKINS-60537] Sanitize label
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/podTemplateWithMultipleLabels.groovy
Labels: bug

#682 Separate authentication tokens
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
Labels: enhancement

#685 Use enhanced PV support in Kind 0.7.0
  kind.sh
Labels: test

#689 Fix ContainerExecDecoratorTest#testCommandExecution
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Labels: test

#691 Fix some exceptions in reaper when receiving an event while jenkins instance is down
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
Labels: bug

#690 Kind improvements
  kind.sh
Labels: chore

#687 Merge pull request #687 from timothydowney/bugfix/sanitize-label-end
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateTest.java
Labels: bug

#683 [JENKINS-60733] Feature/collapse configuration
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: enhancement

#693 Rely on bom for step-api
  pom.xml
Labels: dependencies

#696 Suppressing testCommandExecution as too flaky
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Labels: test

#694 [JENKINS-60798] Assume skipTlsVerify is true if ca certificate i…
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java
Labels: bug

#698 Merge pull request #698 from Dohbedoh/JENKINS-60886
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarative.groovy
Labels: enhancement

#700 [JENKINS-60937] Pods are not created due to 'invalid label value: "jenkins/slave-default"'
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
Labels: bug
