Repository jenkinsci/kubernetes-plugin, pull requests merged in 2020-08, with the labels that each got.

#811 JENKINS-62788 Remove custom f:checkbox fork
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/form/checkbox.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/form/taglib
Labels: enhancement

#812 Suggest NodeProvisioner review after adding new pods
  src/main/java/io/jenkins/plugins/kubernetes/NoDelayProvisionerStrategy.java
Labels: enhancement

#819 Remove explicit versions-maven-plugin
  pom.xml
  src/test/resources/rules.xml
Labels: chore

#815 [JENKINS-61306] Fix: HostNetwork always displayed and reset to false …
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
Labels: bug

#818 [JENKINS-59690] Fix: allow multiple labels also in Jenkinsfile
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecutionTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/badlabel.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarative.groovy
Labels: enhancement

#821 Prevent fragmentation of kube exec calls by bumping the container exec buffer size to 16 kb
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
Labels: enhancement

#822 [JENKINS-63441] Give the right ACL to the reaper in order to see everything in the queue
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
Labels: bug

#823 Add a cloud instance automatically when running in hpi:run mode
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Labels: enhancement

#828 Don't provision when concurrency limit is 0
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: bug
