Repository jenkinsci/kubernetes-plugin, pull requests merged in 2020-04, with the labels that each got.

#751 Warn about permissions needed by DynamicPVCWorkspaceVolume
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume/config.jelly
Labels: documentation

#756 Fix logging
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Labels: bug

#755 Fix NPE in Reaper
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
Labels: bug

#750 Prevent NPE when null set in container's volume mounts
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
Labels: bug

#759 Looks like in some case of workspace reuse the executable exist but don't have right permission
  kind.sh
Labels: chore

#758 [JENKINS-61930] JCasC testing
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/CasCTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/EnvVarCasCTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/VolumeCasCTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/WorkspaceVolumeCasCTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_envVar_keyValue.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_envVar_secret.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_volume_configMap.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_volume_emptyDir.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_volume_emptyDir_memory.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_volume_hostPath.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_volume_nfs.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_volume_pvc.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_workspaceVolume_dynamicPVC.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_workspaceVolume_emptyDir.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_workspaceVolume_emptyDir_memory.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_workspaceVolume_hostPath.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_workspaceVolume_nfs.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/casc_workspaceVolume_pvc.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/configuration-as-code.yaml
Labels: test

#762 Bump bom to 2.222.x as suggested by @jglick
  pom.xml
Labels: dependencies

#761 We shouldn't need these exclusions anymore thanks to new hpi plugin
  pom.xml
Labels: chore

#763 Removing some properties which are unnecessary as of 4.x parent
  pom.xml
Labels: chore

#767 Handle odd job names that do not match DNS_SUBDOMAIN
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlaveTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodNameTest.java
Labels: bug

#764 Update kubernetes-client-api to 4.9.1-1
  pom.xml
Labels: dependencies

#768 Too much INFO logging
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
Labels: enhancement

#771 Remove KubernetesPipelineTest.runInPodWithDifferentShell
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithDifferentShell.groovy
Labels: test

#769 Log waiting loop every 30 seconds
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Labels: enhancement

#757 Rework containerExec output streams
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
Labels: enhancement

#770 Don't disconnect before deleting pod
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Labels: enhancement
