Repository jenkinsci/kubernetes-plugin, pull requests merged in 2020-10, with the labels that each got.

#853 `PodTemplateUtils#combine` shouldn't have a side-effect on the parent pod template
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Labels: bug

#856 Iterate on `RestartPipelineTest#taskListenerAfterRestart` flakiness
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Labels: test

#852 Remove empty help file introduced in #775 by mistake
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-nodeProperties.html
Labels: bug

#861 [JENKINS-58463] Allow maxConcurrentRequests to go above 64
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
Labels: bug

#858 Print a warning in build log for declarative deprecated options
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy
Labels: enhancement

#866 Fix: Concurrency limit 0 must mean unlimited for upgradeability
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-containerCapStr.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: bug

#874 Hacktoberfest - Fixup docker image name and tag
  README.md
  README_zh.md
  examples/dood.groovy
  examples/kaniko-declarative.groovy
  examples/kaniko-gcr.groovy
  examples/kaniko.groovy
  examples/openshift-home-yaml.groovy
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-directConnection.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_0_12/config.xml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_0_8/config.xml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_10/config.xml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_1/config.xml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_9/config.xml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_15_9_invalid/config.xml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest/upgradeFrom_1_17_2/config.xml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVC.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInDynamicallyCreatedContainer.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithLivenessProbe.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithMultipleContainers.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithCloudOverriddenNamespace.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithStepOverriddenNamespace.groovy
Labels: enhancement, hacktoberfest-accepted

#868 readme: add instructions for running with OpenShift 3
  README.md
Labels: chore

#877 Fix PodTemplate hygiene on default values
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: enhancement
