Repository jenkinsci/kubernetes-plugin, pull requests merged in 2021-06, with the labels that each got.

#1004 Clarify docs regarding `command` and `args`
  README.md
Labels: documentation

#935 Update kubernetes-client-api to 5.4.1
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/TaskListenerEventWatcher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepExecution.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
Labels: dependencies

#1003 Round of review on the documentation
  README.md
  examples/containerLog.groovy
  examples/declarative_from_yaml_file/KubernetesPod.yaml
  examples/dind.groovy
  examples/dood.groovy
  examples/kaniko-declarative.groovy
  examples/kaniko-gcr.groovy
  examples/kaniko.groovy
  examples/maven-with-cache-pvc.yml
  examples/maven-with-cache.groovy
  examples/multi-container.groovy
  examples/openshift-home-yaml.groovy
  examples/selenium.groovy
  images/mypod.png
Labels: documentation

#1009 Use `SecretPatterns` from `SecretsMasker`
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: enhancement

#1008 [JENKINS-65908] Backport kubernetes-client-api 5.x compatibility for old Jenkins users
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/TaskListenerEventWatcher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepExecution.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
Labels: enhancement
