Repository jenkinsci/kubernetes-plugin, pull requests merged in 2021-10, with the labels that each got.

#1028 JENKINS-66484 - Tentative fix of a race condition in KubernetesProvisioningLimits
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimits.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimitsTest.java
Labels: bug

#923 [JENKINS-63847] Use line separator from agent OS instead of master OS
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
Labels: bug

#1041 Run release drafter with GH actions
  .github/workflows/release-drafter.yml
Labels: chore

#1024 JENKINS-46253 Including support for subPath in configMaps Volumes
  .gitignore
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/ConfigMapVolume.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/ConfigMapVolume/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/ConfigMapVolume/help-subPath.html
Labels: enhancement
