Repository jenkinsci/kubernetes-plugin, pull requests merged in 2021-11, with the labels that each got.

#1058 Fixes an ArrayOutOfBoundException on node launch failure
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Labels: bug

#1056 Fixed some deprecation warnings and minor refactoring
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/NonConfigurableKubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodAnnotation.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodImagePullSecret.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodLabel.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimitsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateFilterTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateMapTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/CasCTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: enhancement

#1055 Replaced jsr-305 annotations with spotbugs annotations
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerEnvVar.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/DefaultInProvisioning.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/InProvisioning.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimits.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodEnvVar.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodLabel.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateFilter.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateLabelFilter.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateSource.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateMap.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/DefaultNodeSelector.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/DefaultRestartPolicy.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/DefaultWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/PodDecorator.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Merge.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/Overrides.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/YamlMergeStrategy.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/EmptyDirVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/NfsVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/PersistentVolumeClaim.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/EmptyDirWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/NfsWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/PersistentVolumeClaimWorkspaceVolume.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapperTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/MetricNamesTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateFilterTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineOverridenNamespaceTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/NoDelayProvisionerStrategyTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/decorator/PodDecoratorTest.java
Labels: enhancement

#1057 Make ingress compatible with K8s v1.22 (expects minimum v1.19 now)
  src/main/kubernetes/jenkins.yml
Labels: chore

#1061 Suppress useless stack trace
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Labels: enhancement

#1065 Fixing test: Labels have been updated from master to built-in
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
Labels: test

#1064 Ensure "Use Jenkins Proxy" is honored in Connection Test
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
Labels: bug

#1067 Relax terminated exit code - can be 137 (SIGKILL) or 143 (SIGTERM)
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#1066 Add note about resuming builds not working with WebSockets
  README.md
Labels: documentation

#1070 De-flake `KubernetesPipelineTest#terminatedPod`
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#1069 Each pod template instance should operate on its own message digest
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
Labels: bug

#1068 Adjust `PodNameTest#trailingDots` to SECURITY-2424
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodNameTest.java
Labels: test

#1072 [JENKINS-64628] Add some diagnostics logging when registering/re-registering pod templates through DSL
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateMap.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
Labels: enhancement

#1074 Restore serial compatibility with 1.30.8 and before
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
Labels: bug

#1076 Fix typo in README
  README.md
Labels: documentation

#1075 [JENKINS-67160] Don't fail if not able to retrieve container logs when the pod is terminated
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodUtils.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/terminatedPod.groovy
Labels: bug

#1077 [JENKINS-67196] Pods are terminated after ~110s and ignore PodTemplate.connectionTimeout when containers start
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
Labels: bug
