Repository jenkinsci/kubernetes-plugin, pull requests merged in 2021-01, with the labels that each got.

#657 Allow reading logs and events with Computer.EXTENDED_READ instead of Jenkins.ADMINISTER
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
Labels: enhancement

#927 Avoid streaming to 2 similar OutputStreams
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Labels: bug

#928 [JENKINS-58631] Document `defaultContainer` for declarative
  README.md
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent/help-defaultContainer.html
Labels: documentation

#930 [JENKINS-63976] Avoid canceling build if resourcequota exceeded or conflict
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Labels: bug

#933 [JENKINS-61950] [CPLT2-6470] unfixing $$ in env vars for sh step inside a container step
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/envVarDollarSignEscaping.groovy
Labels: bug

#925 [JENKINS-63627] container() defines `POD_CONTAINER` in its body with the name of the container
  README.md
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPod.groovy
Labels: enhancement

#929 [JENKINS-61072] Merge init containers
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Labels: bug

#924 [JENKINS-62502] `ContainerExecDecorator` should escape double quotes
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Labels: bug
