Repository jenkinsci/kubernetes-plugin, pull requests merged in 2021-05, with the labels that each got.

#994 [JENKINS-65398] some terminology changes.
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodRetention.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config_zh_CN.properties
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-podRetention.html
Labels: chore

#993 add default value for command & args in README document
  README.md
Labels: documentation

#991 Reduce guava footprint
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesClientProvider.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimits.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodLabel.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/StandardPlannedNodeBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/EvictingQueue.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
Labels: enhancement

#990 Mask dots in generated pod names
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
Labels: enhancement

#998 Fix broken link for yaml representation of the Pod
  README.md
Labels: documentation

#995 Use linked hashmap to keep container order as defined in pod template
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Labels: bug
