Repository jenkinsci/kubernetes-plugin, pull requests merged in 2021-02, with the labels that each got.

#940 Fix deprecated api calls
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Labels: chore

#945 Upgrade kind to 0.10.0 / k8s 1.20.2
  kind.sh
  src/main/kubernetes/service-account.yml
  test-in-k8s.yaml
Labels: chore

#942 Use stripIndent to keep indentation on inline yamls
  README.md
Labels: documentation

#939 Revamp concurrency limits to rely on Jenkins information only.
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimits.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesProvisioningLimitsTest.java
Labels: enhancement

#947 Configure autolabeler
  .github/autolabeler.yaml
Labels: chore

#953 Prepare update to kubernetes-client by removing imports of class that are going to change
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
Labels: test

#941 Add additional configuration guide for websockets
  README.md
Labels: documentation

#954 docs: fix indentation in yaml examples
  README.md
Labels: documentation

#957 [JENKINS-57841] Typo in defaultValue for ttyEnabled
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly
Labels: bug

#963 Create labels on pod template creation
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateJenkinsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Labels: enhancement

#938 [JENKINS-62502] Escaping double quotes, take 2
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Labels: bug
