Repository jenkinsci/kubernetes-plugin, pull requests merged in 2021-12, with the labels that each got.

#1084 Update dependencies
  pom.xml
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: dependencies

#1081 Bump fabric8 to 5.10.1 and bump with latest release of kubernetes-client-api
  pom.xml
Labels: dependencies

#1080 Just wait for container status to be displayed.
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#1086 Prevent `KubernetesPipelineTest.cascadingDelete` from spuriously failing locally
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  test-in-k8s.yaml
Labels: test

#1085 Externalize inbound-agent version to a Dockerfile so that it is updated automatically
  .github/dependabot.yml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Dockerfile
Labels: enhancement

#1088 Removing unused `AllContainersRunningPodWatcher.runListener`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Labels: enhancement

#1090 Add links to the pod model
  README.md
Labels: documentation

#1087 [JENKINS-66986] Allow non kubernetes nodes to be provisioned inside the container clause
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
Labels: bug

#1091 Move help files to superclass
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/ConfigMapVolume/help-mountPath.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/HostPathVolume/help-mountPath.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/NfsVolume/help-mountPath.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/PersistentVolumeClaim/help-mountPath.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/PodVolume/help-mountPath.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/PodVolume/help-subPath.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume/help-mountPath.html
Labels: chore

#1092 Avoid NPE if container environment is null
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/declarativeFromYamlWithNullEnv.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-jnlp-nullenv.yaml
Labels: bug

#1094 JENKINS-66886 Plugin should respect slaveConnectTimeout
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/AllContainersRunningPodWatcher.java
Labels: bug

#1096 [JENKINS-64628] Avoid ISE from `KubernetesSlave.getTemplate` in `SecretsMasker`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
Labels: bug
