Repository jenkinsci/kubernetes-plugin, pull requests merged in 2022-08, with the labels that each got.

#1212 [JENKINS-67664][JENKINS-59652] Add retry mechanism for container exec…
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
Labels: bug

#1219 Robustness of `SecretsMasker` looking up `KubernetesComputer`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
Labels: bug

#1184 Document necessary k8s Role rules for plugin
  README.md
Labels: documentation

#1230 Simplify `dependencyManagement`
  pom.xml
Labels: dependencies

#1231 Plugin cannot compile with Java 11
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
Labels: bug

#1235 Increase kind stage timeout to 90 minutes.
  Jenkinsfile
Labels: chore

#1236 Display the cloud name for non-configurable kubernetes clouds to help distinguish between multiple instances.
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/NonConfigurableKubernetesCloud/config.jelly
Labels: enhancement
