Repository jenkinsci/kubernetes-plugin, pull requests merged in 2022-12, with the labels that each got.

#1274 Prefer `getTemplateOrNull` to `getTemplate`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
Labels: bug

#1273 wait for docker daemon to start in dind example to avoid error
  examples/dind.groovy
Labels: documentation

#1275 Update baseline, POM, BOM, Kind, etc.
  .github/dependabot.yml
  README.md
  README_zh.md
  examples/openshift-home-yaml.groovy
  kind.sh
  kind.yaml
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Dockerfile
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
  src/test/java/org/jvnet/hudson/test/JenkinsRuleNonLocalhost.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/cascadingDelete.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVCVolume.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVCWorkspaceVolume.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/jnlpWorkingDir.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInDynamicallyCreatedContainer.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithLivenessProbe.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInPodWithMultipleContainers.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithCloudOverriddenNamespace.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithStepOverriddenNamespace.groovy
  test-in-k8s.yaml
Labels: dependencies

#1277 Let `runInDynamicallyCreatedContainer` work with cgroups v2
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runInDynamicallyCreatedContainer.groovy
Labels: test
