Repository jenkinsci/kubernetes-plugin, pull requests merged in 2022-01, with the labels that each got.

#1102 EOL JSR 305
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/DynamicPVCVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume.java
Labels: chore

#1103 Fix requireUpperBoundDeps
  pom.xml
Labels: chore

#1109 Removing unused `ContainerExecDecorator.ws`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java
Labels: enhancement

#1111 Some `@CheckForNull`s
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
Labels: enhancement

#1106 Order requireUpperBoundDeps and document conflicts
  pom.xml
Labels: chore

#1110 Removing comment about `Reaper` rendered incorrect by #714
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Labels: test

#1112 `KubernetesTestUtil.setupHost` should call `KubernetesCloud.setJenkinsUrl` not `JenkinsLocationConfiguration.setUrl`
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Labels: test

#1113 `KubernetesPipelineTest.containerTerminated` sometimes fails to print `Reason: OOMKilled`
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#1123 README: Adding a troubleshooting entry
  README.md
Labels: documentation

#1124 Fixing README format, missing quotes.
  README.md
Labels: documentation
