Repository jenkinsci/kubernetes-plugin, pull requests merged in 2022-09, with the labels that each got.

#1243 `KubernetesFolderProperty` threw NPE on a `WorkflowMultiBranchProject`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty.java
Labels: bug

#1245 Remove dead code
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorConditionTest.java
Labels: chore

#1241 Remove note about old and fixed issue
  README.md
Labels: documentation

#1228 [JENKINS-69306] fix: add the System Info menu item to allow administrator to view agent properties when running
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/sidepanel2.jelly
Labels: bug
