Repository jenkinsci/kubernetes-plugin, pull requests merged in 2022-04, with the labels that each got.

#1160 Ensure yaml > template > cloud for namespace
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pod-overrides.yaml
Labels: bug

#1158 Remove dead code
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
Labels: chore

#1155 JENKINS-56687: Restrict pipeline support to authorised folders fix
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesQueueTaskDispatcher.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Messages.properties
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesQueueTaskDispatcherTest.java
Labels: enhancement
