Repository jenkinsci/kubernetes-plugin, pull requests merged in 2023-11, with the labels that each got.

#1457 Refresh of inline docs
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-image.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-name.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-directConnection.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-jnlpregistry.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Messages.properties
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-slaveConnectTimeout.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent/help-defaultContainer.html
Labels: documentation

#1470 BOM cleanup
  pom.xml
Labels: dependencies

#1471 [JENKINS-72314] Fix cloud save and roundtrip test
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: bug

#1472 [JENKINS-72314] Tidy up previous changes
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
Labels: bug

#1474 Use background cascading deletion of DynamicPVC
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/DynamicPVC.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: enhancement

#1475 [JENKINS-70217] Default ContainerTemplate command and arg to empty string when using casc.
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/CasCTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/configuration-as-code.yaml
Labels: bug
