Repository jenkinsci/kubernetes-plugin, pull requests merged in 2023-07, with the labels that each got.

#1348 Set offline cause when Pod is terminated
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodOfflineCause.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Messages.properties
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/ReaperTest.java
Labels: enhancement

#1400 feat: system property to disable no delay provisioner cloud shuffle
  README.md
  src/main/java/io/jenkins/plugins/kubernetes/NoDelayProvisionerStrategy.java
Labels: enhancement

#1402 Fix no delay provisioner search
  src/main/java/io/jenkins/plugins/kubernetes/NoDelayProvisionerStrategy.java
Labels: bug

#1406 [JENKINS-71639] Allow injecting a securityContext for jnlp containers when using restricted PSS
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-restrictedPssSecurityContext.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Labels: feature
