Repository jenkinsci/kubernetes-plugin, pull requests merged in 2023-03, with the labels that each got.

#1330 Upgrade kubernetes-client-api to 6.4.1-215.v2ed17097a_8e9
  pom.xml
Labels: enhancement, dependencies

#1335 Send diag to build log when `KubernetesAgentErrorCondition` does not match
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorConditionTest.java
Labels: enhancement

#1337 [JENKINS-70416] Ensure auto-configure is disabled when auth is provided
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java
Labels: bug

#1340 Update parent
  pom.xml
Labels: chore
