Repository jenkinsci/kubernetes-plugin, pull requests merged in 2023-10, with the labels that each got.

#1429 Remove unnecessary test branch
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#1366 Handle the case when `watch.exitCode` may return null
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecProc.java
Labels: bug

#1451 Added `DirectConnectionTest`, downgrading agent image
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Dockerfile
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/DirectConnectionTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/directConnectionAgent.groovy
  test-in-k8s.sh
Labels: dependencies

#1443 [JENKINS-72176] Split cloud management page into multiple pages
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/new.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/sidepanel.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/sidepanel.properties
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/templates.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Messages.properties
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/index.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/sidepanel.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/sidepanel.properties
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: enhancement
