Repository jenkinsci/kubernetes-plugin, pull requests merged in 2023-02, with the labels that each got.

#1304 Do not ask API server for a `Pod` during deletion unnecessarily
  Jenkinsfile
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Always.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Default.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Never.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/OnFailure.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodRetention.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/PodRetentionTest.java
Labels: bug

#1308 Fix tests for the upcoming LTS
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: test

#1312 Tweak renovate configuration
  .github/renovate.json
Labels: chore

#1315 Remove jdk11 suffix from inbound-agent to ease matching
  .github/renovate.json
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Dockerfile
Labels: chore

#1320 [JENKINS-70563] Adapt proxy configuration to Kubernetes client 6.x
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java
Labels: bug

#1305 Improve PodTemplate name and inheritFrom help messages
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-inheritFrom.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-name.html
Labels: enhancement, documentation

#1306 Upgrade kubernetes-client-api to 6.4.x line
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/WithContextClassLoader.java
Labels: enhancement, dependencies

#1324 Give more time to agent to reconnect after a restart in CI
  pom.xml
Labels: test

#1325 Ignore `RestartPipelineTest` until I sort out the test issue
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Labels: test
