Repository jenkinsci/kubernetes-plugin, pull requests merged in 2023-01, with the labels that each got.

#1284 Pre-load test docker images to prevent timeouts during tests
  kind.sh
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/kubectlBuildWrapper_invalidCredentials.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/kubectlBuildWrapper_missingCredentials.groovy
Labels: test

#1286 NPE from `KubernetesSlave.getKubernetesCloud`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Labels: bug

#1282 [JENKINS-49707] Document pod retries
  README.md
Labels: documentation

#1260 Upgrade kubernetes-client-api to 6.x
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecProc.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepExecution.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/ReaperTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/mergeYaml.groovy
  test-in-k8s.yaml
Labels: enhancement, dependencies

#1289 [JENKINS-70392] Kubernetes client 6.x follow-up compatibility
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineRJRTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineRJRTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineWebsocketRJRTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/steps/AssertBuildStatusSuccess.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/steps/CreateWorkflowJobThenScheduleRun.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/steps/RunId.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/steps/SetupCloud.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/steps/package-info.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/basicPipeline.groovy
Labels: bug

#1291 [JENKINS-70392] Compatibility fix with kubernetes-client 6.x (again)
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/WithContextClassLoader.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
Labels: bug

#1292 Run CI in parallel
  Jenkinsfile
  kind.sh
  test-in-k8s.sh
Labels: chore

#1293 Slightly relax `runInPodWithMultipleContainers` as it breaks with custom image
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#1294 use a container-based node for the initial split
  Jenkinsfile
Labels: chore

#1290 [JENKINS-70392] RealJenkinsRule testing
  pom.xml
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineRJRTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineRJRTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineWebsocketRJRTest.java
  src/test/java/org/jvnet/hudson/test/JenkinsRuleNonLocalhost.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/basicPipeline.groovy
Labels: test

#1296 Trying again to make `KubernetesSamples` optional
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesSamples.java
Labels: bug

#1299 `Cloud.name` should be part of `equals/hashCode`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: bug

#1301 Add support for `serverCertificate` base64-encoded, such as what is provided by Amazon EKS
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-serverCertificate.html
Labels: enhancement

#1302 [JENKINS-70493] Disable Kubernetes client autoconfiguration when an URL is provided
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
Labels: bug
