Repository jenkinsci/kubernetes-plugin, pull requests merged in 2023-04, with the labels that each got.

#1349 Jenkins design library symbols
  Dockerfile
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/sidepanel2.jelly
Labels: enhancement

#1356 Minor cleanups from SECURITY-3079 fix
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/SecretsMasker.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: chore

#1352 Remove duplicated help button around Workspace Volume in Pod Template details
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
Labels: bug

#1344 Clarify in warning message why `retry` might have declined to do so
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java
Labels: documentation

#1354 Activate `KubernetesAgentErrorCondition` when `podTemplate {node {…}}` fails to connect
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java
Labels: bug

#1361 EOL JSR 305
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineOverridenNamespaceTest.java
Labels: chore
