Repository jenkinsci/kubernetes-plugin, pull requests merged in 2023-08, with the labels that each got.

#1415 fix KubernetesCloudTest as configuration page was moved
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: developer

#1417 `KubernetesPipelineTest.errorPod` flake revealed bug in `Reaper`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: bug

#1418 Follow up #1415
  pom.xml
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
Labels: test

#1420 `KubernetesSlave#readResolve` should call super implementation
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
Labels: bug

#1392 Add more spotbugs checks and fix existing issues
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerEnvVar.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerLivenessProbe.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFolderProperty.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/MetricNames.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/OpenShiftTokenCredentialImpl.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateToolLocation.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodVolumes.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PortMapping.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ServiceAccountCredential.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecorator.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerLogStepExecution.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerStepExecution.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/NamespaceAction.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateAction.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/OnFailure.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/ConfigMapVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/DynamicPVCVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/EmptyDirVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/HostPathVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/NfsVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/PersistentVolumeClaim.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/DynamicPVCWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/EmptyDirWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/HostPathWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/NfsWorkspaceVolume.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/PersistentVolumeClaimWorkspaceVolume.java
Labels: bug

#1342 Upgrade kubernetes-client-api to 6.8.1
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
  src/spotbugs/excludesFilter.xml
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/ReaperTest.java
Labels: enhancement

#1425 Remove unnecessary exclusions
  pom.xml
Labels: skip-changelog
