Repository jenkinsci/kubernetes-plugin, pull requests merged in 2024-01, with the labels that each got.

#1490 Require 2.426.1 LTS or newer
  pom.xml
Labels: dependencies, internal

#1494 Introduce `KubernetesDeclarativeAgentRJRTest`
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentRJRTest.java
Labels: test

#1503 [JENKINS-71956] Octal notation fixes
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest/decimal.yaml
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest/octal.yaml
Labels: bug

#1506 Properly unregister slots that were reserved during provisioning if the provisioning ended up failing.
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/LimitRegistrationResults.java
Labels: bug

#1491 [fix_non_config_instance] add no-op methods for non readonly Kubernetes cloud
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/NonConfigurableKubernetesCloud.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/NonConfigurableKubernetesCloudTest.java
Labels: bug

#1507 Update kubernetes-client api to 6.10.0
  pom.xml
Labels: enhancement, dependencies
