Repository jenkinsci/kubernetes-plugin, pull requests merged in 2024-10, with the labels that each got.

#1608 Use current context for validation functions
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudFIPSTest.java
Labels: enhancement

#1610 Update source code url for docker-inbound-agent
  README.md
  README_zh.md
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/help-image.html
Labels: documentation

#1614 Copy the whole `/usr/share/jenkins` path recursively to account for extra files
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
Labels: enhancement

#1613 Use configured registry for jenkins-agent when running in agent-injection mode
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Labels: bug
