Repository jenkinsci/kubernetes-plugin, pull requests merged in 2024-03, with the labels that each got.

#1516 Fix flake on `ReaperTest#testRemoveWatchWhenCloudRemoved`
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/ReaperTest.java
Labels: test, developer

#1519 Enforce consistent versions for mock libraries
  pom.xml
Labels: chore

#1520 Add `PodTemplateGroup#addTemplate`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateGroup.java
Labels: developer

#1513 [JENKINS-72112] Allow merge strategy inheritance in PodTemplates
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStepExecution.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/help-inheritYamlMergeStrategy.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/casc/CasCTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/casc/configuration-as-code.yaml
Labels: enhancement

#1522 Follow-up JENKINS-72112; Spotbugs annotations
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgent.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/yaml/YamlMergeStrategy.java
Labels: chore

#1525 [JENKINS-72886] fix `command` & `args` are lost when combining container templates
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtilsTest.java
Labels: bug
