Repository jenkinsci/kubernetes-plugin, pull requests merged in 2024-05, with the labels that each got.

#1542 `openjdk` images are deprecated and they have started removing old tags
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/runWithEnvVariables.groovy
Labels: test

#1541 Unwrap advanced configuration section
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
Labels: enhancement

#1543 Garbage collection of orphan pods
  README.md
  images/garbage-collection.png
  pom.xml
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/GarbageCollection.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateUtils.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/GarbageCollection/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/GarbageCollection/help-namespaces.html
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/help-garbageCollection.html
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/garbageCollection.groovy
Labels: enhancement

#1547 Remove reference to `MIME_TYPES`
  src/test/java/org/jvnet/hudson/test/JenkinsRuleNonLocalhost.java
Labels: chore

#1549 Better test robustness
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: test

#1550 Label dynamic PVC with same labels as pod; Filter down lists to current test to ease parallel testing.
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/DynamicPVC.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVCVolume.groovy
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/dynamicPVCWorkspaceVolume.groovy
Labels: enhancement

#1495 Allow Kind tests to mount `~/.m2/`
  README.md
  kind-mount-m2.sh
  kind-preload.sh
  kind.sh
  test-in-k8s-pvc.yaml
  test-in-k8s.sh
  test-in-k8s.yaml
Labels: test

#1552 Fixed a few IDE warnings while poking around this class, and use JDK11 `Set#of`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesAgentErrorCondition.java
Labels: chore

#1546 [JENKINS-73103] Prepare plugin to allow users with overall/manage to manage clouds/pod/container templates
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/new.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/sidepanel.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/templates.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/container.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/events.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/podLog.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesComputer/sidepanel2.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/index.jelly
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/PodTemplate/sidepanel.jelly
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: enhancement

#1553 Add `--noReconnectAfter 1d` option when available in the agent image.
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilder.java
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/Dockerfile
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
Labels: enhancement

#1557 Handle case where a node is launched with an invalid template
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Labels: bug

#1556 Update code snippets with retry step
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/declarative.groovy
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/maven.groovy
  src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/samples/windows.groovy
Labels: enhancement

#1559 Remove usages of Commons Compress
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesTestUtil.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplateBuilderTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/ContainerExecDecoratorPipelineTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/RestartPipelineTest.java
Labels: test, developer

#1561 [JENKINS-73224] Do not try to create a pod which already exists
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/AbstractKubernetesPipelineRJRTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentRJRTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineRJRTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineWebsocketRJRTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/steps/AssertBuildLogMessage.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/steps/CreateWorkflowJobThenScheduleTask.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/restartDuringPodLaunch.groovy
  test-in-k8s.yaml
Labels: bug

#1563 Add a dummy descriptor for `KubernetesLauncher`
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java
Labels: bug

#1560 Handle pods that have been evicted via the eviction API.
  kind.sh
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/pod/retention/Reaper.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/handleEviction.groovy
  test-in-k8s.yaml
Labels: enhancement
