Repository jenkinsci/kubernetes-plugin, pull requests merged in 2024-09, with the labels that each got.

#1604 [JENKINS-73788] Reduce metrics bloat relating to provisioning requests
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/MetricNames.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/MetricNamesTest.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesPipelineTest.java
Labels: bug

#1605 [JENKINS-73789] empty certificate is valid now
  src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java
  src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudFIPSTest.java
  src/test/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloudFIPSTest/nonCompliantCloudsAreCleanedTest/config.xml
Labels: chore

#1606 Update README with agent injection in mind
  README.md
  images/mypod-1-general.png
  images/mypod-2-golang.png
  images/mypod-3-maven.png
  images/mypod.png
  images/pod-template-configuration.png
Labels: documentation
